# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Distribution information.

This file is typically auto-generated by the build system, but for the purposes
of bootstrapping, we are including it inline for the moment.
"""

import importlib.util
import os
import subprocess
import sys
from pathlib import Path

# Some downstream users of these APIs do not expect or handle
# stdout/stderr output from this code, so logging is disabled by default.
# See https://github.com/ROCm/TheRock/issues/3109.
_VERBOSE = os.getenv("ROCM_SDK_VERBOSE", "0") == "1"

CACHED_TARGET_FAMILY: str | None = None


class LibraryEntry:
    """Defines a public library that can be located by name within the overall
    distribution."""

    def __init__(
        self,
        shortname: str,
        package_name: str,
        so_pattern: str,
        dll_pattern: str,
        posix_relpath="lib",
        optional: bool = False,
    ):
        self.shortname = shortname
        self.package = ALL_PACKAGES[package_name]
        self.posix_relpath = posix_relpath
        self.windows_relpath = "bin"
        self.so_pattern = so_pattern
        self.dll_pattern = dll_pattern
        # Optional libraries may be absent from a built distribution (e.g.
        # rocdxg only builds on a WSL host and is skipped on fork PRs and
        # local single-command Linux builds). find_libraries skips these
        # rather than raising when no file matches.
        self.optional = optional
        assert shortname not in ALL_LIBRARIES
        ALL_LIBRARIES[shortname] = self

    def __repr__(self):
        return f"{self.shortname}(so_pattern={self.so_pattern}, dll_pattern={self.dll_pattern}, package={self.package})"


class PackageEntry:
    """Defines a package known to the SDK.

    Args:
      logical_name: Short name referring to this package within the SDK.
      dist_package_name: Templated dist package name, including '{target_family}' if
        GPU target specific.
      pure_py_package_name: Name of the pure-python API package. All GPU target specific
        dist packages will export the same pure-python package. Since they are
        identical, first wins.
      template_directory: Directory name in the build system that provides the template
        for this package.
      required: Whether this package is required.
    """

    def __init__(
        self,
        logical_name: str,
        dist_package_template: str,
        *,
        pure_py_package_name: str,
        template_directory: str,
        required: bool = False,
    ):
        self.logical_name = logical_name
        self.dist_package_template = dist_package_template
        self.pure_py_package_name = pure_py_package_name
        self.template_directory = template_directory
        self.required = required
        if logical_name in ALL_PACKAGES:
            raise ValueError(f"Package already defined: {logical_name}")
        ALL_PACKAGES[logical_name] = self

    @property
    def is_target_specific(self) -> bool:
        return "{target_family}" in self.dist_package_template

    def get_dist_package_name(self, target_family: str | None = None) -> str:
        if self.is_target_specific and target_family is None:
            raise ValueError(
                f"Package {self.logical_name} is target specific, but no target specified"
            )
        kwargs = {}
        if target_family is not None:
            # Strip xnack suffix (e.g., 'gfx942:xnack+' -> 'gfx942') for valid package names
            kwargs["target_family"] = target_family.split(":")[0]
        return self.dist_package_template.format(**kwargs)

    def get_dist_package_require(self, target_family: str | None = None) -> str:
        return self.get_dist_package_name(target_family) + f"=={__version__}"

    def get_py_package_name(self, target_family: str | None = None) -> str:
        dist_name = self.get_dist_package_name(target_family)
        return "_" + dist_name.replace("-", "_") + PY_PACKAGE_SUFFIX_NONCE

    def get_py_package(self, target_family: str | None = None):
        return importlib.util.find_spec(self.get_py_package_name(target_family))

    def has_py_package(self, target_family: str | None = None) -> bool:
        return self.get_py_package(target_family) is not None

    def __repr__(self):
        return self.dist_package_template


def discover_current_target_family() -> str | None:
    """Attempts to query the current target family via the 'offload-arch' tool."""

    try:
        import sysconfig

        # offload-arch is expected to be installed in the Python 'scripts'
        # directory, which will vary depending on the platform and whether or
        # not a virtual environment is used, for example:
        #   Linux system:   /usr/local/bin
        #   Linux venv:     .venv/bin
        #   Windows system: C:\Users\...\Python313\Scripts
        #   Windows venv:   .venv\Scripts
        # It might also be provided by an install of LLVM (e.g. as part of
        # Visual Studio on Windows), so prepend the scripts dir to PATH.
        scripts_path = Path(sysconfig.get_path("scripts"))
        env = os.environ.copy()
        env["PATH"] = str(scripts_path) + os.path.pathsep + env.get("PATH", "")
        result = subprocess.check_output(
            ["offload-arch"], env=env, text=True, stderr=subprocess.STDOUT
        )

        if result:
            arch_set = set(result.strip().split("\n"))
            suffixes = ["-all", "-dgpu", "-igpu", "-dcgpu"]
            for arch in arch_set:
                # There may be multiple architecture supported on the system.
                # This will select the first matching family.
                arch_family = arch[:-1] + "X"
                for suffix in suffixes:
                    target_family = arch_family + suffix
                    if target_family in AVAILABLE_TARGET_FAMILIES:
                        return target_family
                if arch in AVAILABLE_TARGET_FAMILIES:
                    return arch
    except subprocess.CalledProcessError as e:
        if _VERBOSE:
            print(
                f"[rocm_sdk] offload-arch failed with return code {e.returncode}",
                file=sys.stderr,
            )
            print(f"[rocm_sdk] output: {e.output}", file=sys.stderr)
    except FileNotFoundError:
        if _VERBOSE:
            print("[rocm_sdk] offload-arch not found", file=sys.stderr)
    except Exception as e:
        if _VERBOSE:
            print(f"[rocm_sdk] offload-arch error: {e}", file=sys.stderr)
    return None


# Resolve the build target family. This consults a list of things in increasing
# order of specificity:
#   1. "ROCM_SDK_TARGET_FAMILY" environment variable
#   2. Dynamically discovered/most salient target family on the actual system
#   3. dist_info.DEFAULT_TARGET_FAMILY
def determine_target_family() -> str:
    global CACHED_TARGET_FAMILY
    if CACHED_TARGET_FAMILY is not None:
        return CACHED_TARGET_FAMILY
    target_family = os.getenv("ROCM_SDK_TARGET_FAMILY")
    if target_family is None:
        target_family = discover_current_target_family()
        if target_family is None:
            target_family = DEFAULT_TARGET_FAMILY
    assert target_family is not None
    if target_family not in AVAILABLE_TARGET_FAMILIES:
        raise ValueError(
            f"Requested ROCM_SDK_TARGET_FAMILY={target_family} is "
            f"not available in the distribution (available: "
            f"{', '.join(AVAILABLE_TARGET_FAMILIES)})"
        )
    CACHED_TARGET_FAMILY = target_family
    return target_family


# All packages that are part of the distribution.
ALL_PACKAGES: dict[str, PackageEntry] = {}
ALL_LIBRARIES: dict[str, LibraryEntry] = {}

# Always available packages.
PackageEntry(
    "meta",
    "rocm",
    pure_py_package_name="rocm_sdk",
    template_directory="rocm",
    required=True,
)
PackageEntry(
    "core",
    "rocm-sdk-core",
    pure_py_package_name="rocm_sdk_core",
    template_directory="rocm-sdk-core",
    required=True,
)
PackageEntry(
    "libraries",
    "rocm-sdk-libraries-{target_family}",
    pure_py_package_name="rocm_sdk_libraries",
    template_directory="rocm-sdk-libraries",
    required=False,
)
PackageEntry(
    "device",
    "rocm-sdk-device-{target_family}",
    pure_py_package_name="rocm_sdk_device",
    template_directory="rocm-sdk-device",
    required=False,
)
PackageEntry(
    "devel",
    "rocm-sdk-devel",
    pure_py_package_name="rocm_sdk_devel",
    template_directory="rocm-sdk-devel",
    required=False,
)
PackageEntry(
    "profiler",
    "rocm-profiler",
    pure_py_package_name="rocm_profiler",
    template_directory="rocm-profiler",
    required=False,
)

# TODO(#703,#1057): Use patterns for version suffixes and platform differences too?

# Public libraries.
LibraryEntry("amdhip64", "core", "libamdhip64.so*", "amdhip64*.dll")
# The DLL glob here uses '0' from the version to avoid matching 'hiprtc-builtins'.
# If DLLs with no version suffix are later added we will need a different pattern.
LibraryEntry("hipfile", "core", "libhipfile.so*", "")
LibraryEntry("hiprtc", "core", "libhiprtc.so*", "hiprtc0*.dll")
LibraryEntry("roctx64", "core", "libroctx64.so*", "")
LibraryEntry("rocprofiler-sdk", "core", "librocprofiler-sdk.so*", "")
LibraryEntry("rocprofiler-sdk-roctx", "core", "librocprofiler-sdk-roctx.so*", "")
LibraryEntry("roctracer64", "core", "libroctracer64.so*", "")
LibraryEntry(
    "rocm_sysdeps_liblzma",
    "core",
    "librocm_sysdeps_liblzma.so.*",
    "",
    "lib/rocm_sysdeps/lib",
)
LibraryEntry(
    "rocm-openblas",
    "core",
    "librocm-openblas.so.*",
    "rocm-openblas*.dll",
    "lib/host-math/lib",
)
LibraryEntry("amd_comgr", "core", "libamd_comgr.so*", "amd_comgr*.dll")
LibraryEntry("rocm_kpack", "core", "librocm_kpack.so*", "rocm_kpack*.dll")
LibraryEntry("rocm_smi64", "core", "librocm_smi64.so*", "")
LibraryEntry("rocdecode", "core", "librocdecode.so*", "")
LibraryEntry("rocjpeg", "core", "librocjpeg.so*", "")
LibraryEntry("amd_smi", "core", "libamd_smi.so*", "")
LibraryEntry("rocdxg", "core", "librocdxg*.so*", "", optional=True)
LibraryEntry("rpp", "libraries", "librpp.so*", "")
LibraryEntry("hipblas", "libraries", "libhipblas.so*", "*hipblas*.dll")
LibraryEntry("hipblaslt", "libraries", "libhipblaslt.so*", "*hipblaslt*.dll")
LibraryEntry("hipfft", "libraries", "libhipfft.so*", "hipfft*.dll")
LibraryEntry("hiprand", "libraries", "libhiprand.so*", "hiprand*.dll")
LibraryEntry("hipsparse", "libraries", "libhipsparse.so*", "hipsparse*.dll")
LibraryEntry("hipsparselt", "libraries", "libhipsparselt.so*", "")
LibraryEntry("hipsolver", "libraries", "libhipsolver.so*", "hipsolver*.dll")
LibraryEntry("rccl", "libraries", "librccl.so*", "")
LibraryEntry("miopen", "libraries", "libMIOpen.so*", "MIOpen*.dll")
LibraryEntry("origami", "libraries", "liborigami.so*", "origami*.dll")
LibraryEntry("hipdnn", "libraries", "libhipdnn_backend.so*", "hipdnn_backend*.dll")

# Others we may want:
# hiprtc-builtins
# rocblas
# rocfft
# rocrand
# rocsolver
# rocsparse

# Overall ROCM package version.
__version__ = "DEFAULT"

# Nonce added to the backend packages which encodes the version. This is
# typically empty for development distributions. Only backend packages with
# a matching nonce will be considered for use by this meta package.
PY_PACKAGE_SUFFIX_NONCE: str = "_DEFAULT"

# If a target family cannot be found or is not relevant (i.e. building devel
# packages on a gpu-less system), this is the default target family.
DEFAULT_TARGET_FAMILY: str = "DEFAULT"

# All available target families that this distribution has available.
AVAILABLE_TARGET_FAMILIES: list[str] = []

# Per-platform target family lists. Populated by the build system when the
# rocm sdist is produced from a multi-arch release that knows about both
# platforms' family sets. Empty when unknown (single-platform builds, or
# loading this module before the build system has rewritten it). Consumed
# by setup.py at install time to attach PEP 508 sys_platform markers to
# device extras for platform-exclusive families.
LINUX_TARGET_FAMILIES: list[str] = []
WINDOWS_TARGET_FAMILIES: list[str] = []


def get_target_family_platform_marker(target_family: str) -> str:
    """Returns a PEP 508 sys_platform marker for a target family, or "".

    Used by the rocm setup.py to attach markers to device-gfx* Requires-Dist
    entries when a family is published only for one platform. Returns "" if
    either platform list is empty (single-platform build or only one
    platform participating in a multi-arch release) since there is no
    cross-platform variant to disambiguate from.
    """
    if not LINUX_TARGET_FAMILIES or not WINDOWS_TARGET_FAMILIES:
        return ""
    # Compare base targets (strip xnack suffix) since platform lists may contain
    # xnack-suffixed entries like 'gfx942:xnack+' while we receive base targets.
    base_target = target_family.split(":")[0]
    linux_base_targets = {t.split(":")[0] for t in LINUX_TARGET_FAMILIES}
    windows_base_targets = {t.split(":")[0] for t in WINDOWS_TARGET_FAMILIES}
    in_linux = base_target in linux_base_targets
    in_windows = base_target in windows_base_targets
    if in_linux and not in_windows:
        return 'sys_platform == "linux"'
    if in_windows and not in_linux:
        return 'sys_platform == "win32"'
    return ""


def build_per_target_extras() -> "dict[str, list[str]]":
    """Builds the device-gfx* and device-all entries for EXTRAS_REQUIRE.

    Returns a dict mapping each per-target extra name to its list of
    Requires-Dist strings. For platform-exclusive targets, attaches a
    PEP 508 sys_platform marker so `pip install rocm[device-all]` only
    pulls device wheels published for the user's OS.

    Returns an empty dict when no target-specific package exists or the
    distribution covers a single target (legacy single-arch behavior;
    the generic extras already in setup.py's EXTRAS_REQUIRE suffice).
    """
    result: dict[str, list[str]] = {}
    # Deduplicate by base target (strip xnack suffix) to avoid redundant iterations
    # when both 'gfx942' and 'gfx942:xnack+' exist in AVAILABLE_TARGET_FAMILIES.
    base_targets = sorted(set(tf.split(":")[0] for tf in AVAILABLE_TARGET_FAMILIES))
    if len(base_targets) <= 1:
        return result
    for pkg in ALL_PACKAGES.values():
        if not pkg.is_target_specific or pkg.required:
            continue
        all_requires: list[str] = []
        for tf in base_targets:
            extra_name = f"{pkg.logical_name}-{tf}"
            req = pkg.get_dist_package_require(target_family=tf)
            marker = get_target_family_platform_marker(tf)
            if marker:
                req = f"{req}; {marker}"
            result[extra_name] = [req]
            all_requires.append(req)
        result[f"{pkg.logical_name}-all"] = all_requires
    return result
