# clr
[components.lib."core/clr/stage"]
exclude = [
  "bin/hsa-runtime64.dll",
]
include = [
  "lib/.hipInfo",
  "share/hip/**",
]
[components.run."core/clr/stage"]
include = [
  "bin/**",
]
exclude = [
  "bin/hsa-runtime64.dll",
  "bin/rocminfo.exe",
  "bin/rocm_agent_enumerator*",
]
[components.dbg."core/clr/stage"]
[components.dev."core/clr/stage"]
exclude = [
  "include/hsa/**",
  "include/hsakmt/**",
  "lib/cmake/hsa-runtime64/**",
  "lib/cmake/hsakmt/**",
  "lib/hsa-runtime64.lib",
  "lib/hsakmt.lib",
  "lib/hsakmt-staticdrm.lib",
  "lib/wkmi.lib",
]
[components.doc."core/clr/stage"]
exclude = [
  "share/doc/rocr/**",
]
