name: Test artifacts

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.12

      - name: Create files
        run: |
          mkdir -p build/artifacts
          cd build/artifacts
          DATE="`date +%Y%m%d-%H%M`"
          touch "testfile1-${DATE}".tar.xz
          sha256sum "testfile1-${DATE}".tar.xz > "testfile1-${DATE}".tar.xz.sha256sum
          touch "testfile2-${DATE}".tar.xz
          sha256sum "testfile2-${DATE}".tar.xz > "testfile2-${DATE}".tar.xz.sha256sum
          touch "testfile3-${DATE}".tar.xz
          sha256sum "testfile3-${DATE}".tar.xz > "testfile3-${DATE}".tar.xz.sha256sum
          touch "testfile1-${DATE}".foo
          touch "testfile2-${DATE}".bar
          touch "testfile3-${DATE}".bla

      - name: Configure AWS Credentials
        if: $${{github.event_name == 'workflow_dispatch' && github.ref =='refs/heads/artifacts' }}
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-artifacts-marbre

      # TODO: Move to script
      - name: Upload Artifacts
        if: $${{github.event_name == 'workflow_dispatch' && github.ref =='refs/heads/artifacts' }}
        run: |
          aws s3 sync build/artifacts s3://therock-artifacts/${{github.run_id}}/ \
            --exclude "*" --include "*.tar.xz" --include "*.tar.xz.sha256sum"

      # TODO: Move to script
      - name: Create and Upload Index
        if: $${{github.event_name == 'workflow_dispatch' && github.ref =='refs/heads/artifacts' }}
        run: |
          curl https://raw.githubusercontent.com/joshbrunty/Indexer/6d8cbfd15d3853b482e6a49f2d875ded9188b721/indexer.py -o build/indexer.py
          python build/indexer.py -f '*.tar.xz*' build/artifacts/
          sed -i 's,a href=",a href="https://therock-artifacts.s3.us-east-2.amazonaws.com/${{github.run_id}}/,g' build/artifacts/index.html
          aws s3 cp build/artifacts/index.html s3://therock-artifacts/${{github.run_id}}/

      - name: Post URL
        if: $${{github.event_name == 'workflow_dispatch' && github.ref =='refs/heads/artifacts' }}
        run: |
          echo '### Artifacts' >> $GITHUB_STEP_SUMMARY
          echo '* [Link to artifacts](https://therock-artifacts.s3.us-east-2.amazonaws.com/${{github.run_id}}/index.html)' >> $GITHUB_STEP_SUMMARY
