# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Copy release to dev bucket

on:
  workflow_dispatch:
    inputs:
      rocm_version:
        description: ROCm version to copy from nightly releases to dev releases, e.g. 7.14.0a20260617 (see https://rocm.nightlies.amd.com/whl-multi-arch/)
        type: string
      python_version:
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        default: "3.12"
      include_torch:
        description: Copy 'torch' packages in addition to 'rocm' packages?
        type: boolean
        default: false
      include_jax:
        description: Copy 'jax' packages in addition to 'rocm' packages?
        type: boolean
        default: false
permissions:
  contents: read

run-name: >-
  Copy nightly -> dev |
  rocm ${{ inputs.rocm_version }} |
  py ${{ inputs.python_version }} |
  extras: ${{
    inputs.include_torch && inputs.include_jax && 'PyTorch + JAX' ||
    inputs.include_torch && 'PyTorch' ||
    inputs.include_jax && 'JAX' ||
    'none'
  }}

jobs:
  copy_python_packages:
    name: Copy nightly -> dev | rocm ${{ inputs.rocm_version }} | py ${{ inputs.python_version }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # TODO: migrate to boto3 Python package instead of this native tool?
      - name: Install the AWS tool
        run: ./dockerfiles/install_awscli.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-dev

      - name: Select Python version
        run: |
          python build_tools/github_actions/python_to_cp_version.py \
            --python-version ${{ inputs.python_version }}

      - name: Copy ROCm packages between S3 buckets
        run: |
          aws s3 cp \
            s3://therock-nightly-python/v4/whl/ \
            s3://therock-dev-python/v4/whl/ \
            --recursive --exclude "*" \
            --include "rocm*${{ inputs.rocm_version }}*"

      - name: Copy torch wheels between S3 buckets
        if: ${{ inputs.include_torch }}
        run: |
          aws s3 cp \
            s3://therock-nightly-python/v4/whl/ \
            s3://therock-dev-python/v4/whl/ \
            --recursive --exclude "*" \
            --include "*torch*${{ inputs.rocm_version }}*${{ env.cp_version }}*" \
            --include "apex*${{ inputs.rocm_version }}*${{ env.cp_version }}*" \
            --include "triton*${{ inputs.rocm_version }}*${{ env.cp_version }}*"

      - name: Copy JAX wheels between S3 buckets
        if: ${{ inputs.include_jax }}
        run: |
          aws s3 cp \
            s3://therock-nightly-python/v4/whl/ \
            s3://therock-dev-python/v4/whl/ \
            --recursive --exclude "*" \
            --include "jax*${{ inputs.rocm_version }}*${{ env.cp_version }}*"
