# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Hip tagging automation

on:
  push:
    branches:
      - main
    paths:
        - rocm-systems

jobs:
  tag-rocm-systems:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout ROCm/TheRock
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.ROCM_SYSTEMS_APP_ID }}
          private-key: ${{ secrets.ROCM_SYSTEMS_APP_PRIVATE_KEY }}
          owner: "ROCm"
          repositories: "rocm-systems"

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Run tagging script
        run: |
          python build_tools/github_actions/hip_tagging_helper.py \
            --repo "${{ github.repository }}" \
            --before "${{ github.event.before }}" \
            --after "${{ github.sha }}" \
            --pat "${{ steps.generate-token.outputs.token }}"
